[versions]

socialismus = "dev-SNAPSHOT"

# compile time processing
lombok = "1.18.32"

# general
guice = "7.0.0"

[libraries]

socialismus = { group = "com.github.whereareiam", name = "Socialismus", version.ref = "socialismus" }

# compile time processing
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

# general
guice = { group = "com.google.inject", name = "guice", version.ref = "guice" }

[bundles]

[plugins]