[versions]

shadow = "9.4.2"
socialismus = "dev-7e469f0"

# compile time processing
lombok = "1.18.46"

# general
annotations = "26.1.0"
guice = "7.0.0"

# testing
junit = "6.1.0"
mockito = "5.23.0"

[libraries]

socialismus-module-api = { group = "me.whereareiam.socialismus.module", name = "api", version.ref = "socialismus" }

# compile time processing
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

# general
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
guice = { group = "com.google.inject", name = "guice", version.ref = "guice" }

# testing
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-platform = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-junit = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }

[bundles]

testing = ["junit-jupiter", "mockito-core", "mockito-junit"]

[plugins]

shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
